#!/bin/bash

# Public environment
TAIGA_PORT=${TAIGA_PORT:-80}
DEBUG=${DEBUG:-True}
PUBLIC_REGISTER_ENABLED=${PUBLIC_REGISTER_ENABLED:-True}
EMAIL_ENABLED=${EMAIL_ENABLED:-False}
EMAIL_DEFAULT_FROM=${EMAIL_DEFAULT_FROM:-noreply@example.com}
EMAIL_USE_TLS=${EMAIL_USE_TLS:-False}
EMAIL_HOST=${EMAIL_HOST:-localhost}
EMAIL_PORT=${EMAIL_PORT:-25}
EMAIL_HOST_USER=${EMAIL_HOST_USER:-user}
EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:-password}


# Private environment varibles
TAIGA_USER=taiga
TAIGA_HOME=/home/taiga
LOG_DIR=$TAIGA_HOME/logs
RABBITMQ_TAIGA_PWD=ratuiersauinrst
RABBITMQ_PORT=5672
TAIGA_SECRET=theveryultratopsecretkey
TAIGA_BACK_API_PORT=8000
TAIGA_EVENTS_PORT=8888
TAIGA_DB_PWD=bupoauiejldv

TAIGA_BACK_COMMIT=stable